"""The architecture deck, as data: one dict per slide. `build_arch_deck.py` renders it to docs/deck/Guardian-Architecture.pptx.

Edit the copy here, then run `python scripts/build_arch_deck.py --export` and look at docs/deck/arch-preview/. Keep the
numbers in step with README.md (the first live sweep) and docs/AWS_SETUP.md (the account state). The slide kinds:
title, columns, table, overview, graph, cards, gate, deployment, closing. Text follows ASD-STE100: short sentences,
active voice, no contractions."""
from __future__ import annotations

from deck_content import AMBER, BLUE, GREEN, INK, LIVE, MUTED_DARK, PAPER, REPO, SLIDES as DEMO_SLIDES  # noqa: F401

GRAPH_SLIDE = next(s for s in DEMO_SLIDES if s["id"] == "graph")

SLIDES: list[dict] = [
    {
        "id": "title",
        "kind": "title",
        "h1": "Recall & Warranty Guardian",
        "sub": "The architecture: gren graphs on the Strands Agents SDK, Claude through the Strands model provider, one human gate, one household.",
        "tagline": "The best output of the agent is silence.",
        "footer_eyebrow": "Agents for Humans · Everyday Agents · Strands Agents SDK · Apache-2.0",
        "footer_mono": f"{REPO}  ·  live: {LIVE}",
        "notes": "The architecture of Recall and Warranty Guardian, for the Agents for Humans hackathon.",
    },
    {
        "id": "problem",
        "kind": "columns",
        "bg": "paper",
        "eyebrow": "Problem and solution",
        "h2": "Recalls reach everyone and match nobody",
        "columns": [
            ("Problem", [
                "Regulators publish thousands of recalls each year. CPSC, NHTSA, and openFDA each have their own feed.",
                "The notices go to everyone. Nobody matches them to the products in one home.",
                "The remedies are free. Most of them stay unclaimed. Warranties expire with claims never filed.",
                "A person does not want another app to check. A person wants one message, one decision, only when it matters.",
            ]),
            ("Solution", [
                "Guardian builds an inventory of the household from forwarded receipts, order emails, and VINs.",
                "Each night, a Strands graph pulls the new recalls, matches them in code, and gives only the ambiguous pairs to a model.",
                "A triage agent and an adversarial verifier decide what deserves an interrupt. The graph stops at one human gate.",
                "After one approval, a side-effect node sends the remedy request with the receipt attached. Then it schedules a follow-up.",
            ]),
        ],
        "stats": [("594", "CPSC recalls in one 400-day window"), ("1,200", "openFDA enforcement reports in the same window"), ("0", "model calls on a quiet night")],
        "notes": "The problem is distribution, not information. The solution is a background agent that matches and files, and speaks only for a decision.",
    },
    {
        "id": "outcomes",
        "kind": "columns",
        "bg": "paper",
        "eyebrow": "Expected outcomes",
        "h2": "What changes for the household",
        "columns": [
            ("Before", [
                "The household hears about a recall by chance, or never.",
                "A recall notice needs a manual search of the model number, the UPC, and the purchase date.",
                "A remedy request needs the receipt, the contact address, and a letter. Most people stop here.",
                "Nobody tracks the warranty window of a blender bought in 2016.",
            ]),
            ("After", [
                "Every night, the inventory is compared with the new recalls. The household sees a quiet score, not a feed.",
                "A critical hazard becomes one SMS with one decision. A standard hazard goes to a weekly digest.",
                "One tap files the remedy request with the receipt. A follow-up runs after 10 business days.",
                "A warranty that ends soon triggers one question: is anything wrong with it?",
            ]),
        ],
        "stats": [("1", "message for each affected item"), ("72 h", "a gate holds a decision, then it expires"), ("10 d", "business days to the follow-up")],
        "notes": "Before: chance and paperwork. After: one message, one tap, and a follow-up the household does not have to remember.",
    },
    {
        "id": "capabilities",
        "kind": "table",
        "bg": "paper",
        "eyebrow": "Agent capabilities",
        "h2": "Four modes, one graph runtime",
        "widths": [300, 330, 620, 450],
        "header": ["Mode", "Trigger", "What it does", "Output"],
        "rows": [
            ["Nightly sweep", "systemd timer at 06:00 UTC, the dashboard logo, or guardian sweep", "Pulls CPSC, NHTSA, and openFDA. Matches in code (UPC, VIN, model, lexical, sold window). A model adjudicates the ambiguous pairs. Triage plans the night. A verifier checks the plan.", "Decisions for the household, a digest, a sweep record, the activity log"],
            ["Intake", "A forwarded receipt, a pasted order email, or a VIN", "Redacts card numbers. Extracts brand, model, UPC, purchase date, retailer, price, and warranty term. Decodes a VIN with NHTSA vPIC.", "One inventory item with a warranty window"],
            ["Household decision", "The gate pauses the run. An SMS link or the dashboard opens the card.", "Shows one card for each affected item: request remedy, no longer own, not mine, snooze. Batches the answers. Releases the gate on the first approval.", "A gate approval with the answers as JSON"],
            ["Remedy and follow-up", "An approved decision", "Writes the request from the remedy text and the contact address of the recall. Sends it one time. Records the action. Schedules the follow-up.", "An email (SES or outbox), an action record, a follow-up date"],
            ["Warranty check-in", "A warranty window that ends within the threshold", "Asks one question at the right time. A reported problem becomes a claim decision.", "A decision card, or silence"],
            ["Agent flow", "Any run, live or past", "Shows the run as the graph executed it: canvas, timeline, events, metrics, gate, spec, and each node. Forks a run from any node.", "The trace workbench in the dashboard"],
        ],
        "notes": "Six capabilities, all on the same runtime. The first four are the product. The workbench is how a person audits the agent.",
    },
    {
        "id": "overview",
        "kind": "overview",
        "bg": "ink",
        "eyebrow": "Solution architecture",
        "h2": "One household, two graphs, one human gate",
        "notes": "Inputs on the left, the two gren graphs in the middle, the household store and the API below, the dashboard and the household on the right, AWS at the bottom.",
    },
    {**GRAPH_SLIDE, "id": "graph", "eyebrow": "Solution architecture · the nightly sweep", "notes": "The nightly sweep is thirteen nodes. Code does the deterministic work. Agents judge. The verifier can reject. The gate pauses."},
    {
        "id": "strands",
        "kind": "cards",
        "bg": "ink",
        "eyebrow": "Runtime",
        "h2": "How a gren graph runs on Strands Agents",
        "cards": [
            ("GraphBuilder", "Every node is a Strands MultiAgentBase executor. gren derives the edges from data references such as $nodes.matcher.outputs. Nobody declares an edge by hand."),
            ("AND joins", "Strands readiness is OR. gren adds an edge condition, so a node runs only when all of its dependencies are complete."),
            ("Structured output", "An agent node runs a Strands Agent with structured_output_model. gren validates the output against the JSON schema and makes one bounded repair call on an invalid output."),
            ("Gates are interrupts", "A BeforeNodeCallEvent hook raises event.interrupt. The run pauses. The checkpoint is on disk. The process can exit. Resume replays completed nodes with no new model calls."),
            ("Verifier with kill authority", "severity_check returns {verdict, reasons, confidence}. A rejection resets triage with the reasons as feedback through a conditional back-edge, at most one round."),
            ("Budgets and side effects", "The engine enforces retries, the fallback model, timeouts, the quorum on fan-outs, and the spend cap. A side-effect node runs one time and only behind an approval."),
        ],
        "footnote": "Every node writes an artifact (system prompt, prompt, schema, raw output, usage, cost) under var/runs/<run>/artifacts. events.jsonl is the trace that the dashboard streams. See ARCHITECTURE.md section 1.",
        "notes": "gren is a thin compiler and a strict engine on top of Strands. The engine owns retries, budgets, gates, and side effects. The model never does.",
    },
    {
        "id": "components-1",
        "kind": "table",
        "bg": "paper",
        "eyebrow": "Components · 1 of 2",
        "h2": "What runs where: the agent",
        "widths": [340, 420, 940],
        "header": ["Component", "Technology", "Description"],
        "rows": [
            ["gren runtime", "Strands Agents SDK, Python", "Compiles a YAML graph into a Strands Graph. Executors, AND joins, budgets, retries, gates, artifacts, events."],
            ["nightly-sweep graph", "gren spec, 13 nodes", "feeds_refresh, expiry_scan, candidate_gen, warranty, matcher, verdicts, triage, severity_check, household_decision, digest, answers, remedy, followup."],
            ["intake graph", "gren spec, 3 nodes", "redact (code), extract (agent, Haiku), save_item (code). A VIN goes through the NHTSA vPIC decoder."],
            ["Feeds", "httpx clients", "CPSC SaferProducts API, NHTSA recalls by vehicle, openFDA food enforcement. Recorded fixtures replay in the tests."],
            ["Matching", "rapidfuzz, code", "Stage 1 exact keys (UPC, vehicle, model). Stage 2 lexical score 80 or more with brand overlap. Stage 3 sold window of plus or minus 60 days. Stage 4 the matcher agent."],
            ["Policy", "code", "Severity keyword pass, notification budget, warranty windows, quiet categories."],
            ["Models", "Claude (Anthropic API today; Amazon Bedrock pending)", "Haiku 4.5 for extraction and verification. Opus 5 for the matcher and triage. Sonnet 5 for the remedy text. Global inference profiles."],
        ],
        "notes": "Seven components make the agent: the runtime, the two graphs, the feeds, the matcher, the policy, and the models.",
    },
    {
        "id": "components-2",
        "kind": "table",
        "bg": "paper",
        "eyebrow": "Components · 2 of 2",
        "h2": "What runs where: the household layer and the surfaces",
        "widths": [340, 420, 940],
        "header": ["Component", "Technology", "Description"],
        "rows": [
            ["Guardian service", "Python", "Turns gate.waiting into Decision rows and SMS. Records answers. Writes the gate approval. Resumes the run. Formats the activity log."],
            ["Household store", "JSON files, DynamoDB-shaped", "items, recalls, matches, decisions, activity, sweeps, outbox, prefs, household. One file per entity under var/household."],
            ["Notifier", "SNS, SES, outbox", "SMS through SNS and email through SES when configured. Otherwise the outbox folder."],
            ["Guardian API", "FastAPI, SSE", "/api for the dashboard, /gren/api for the run workbench, /api/events for live updates. Token gate on writes."],
            ["Dashboard", "Vite, React, TypeScript", "Home, Decisions, Inventory, Activity, Settings, Agent flow. Dark, RTL, mobile. Three fonts, five brand colors."],
            ["Live deployment", "EC2, Caddy, systemd, S3", "One instance with automatic HTTPS. A timer runs the sweep at 06:00 UTC. The store mirrors to the state bucket."],
            ["AgentCore path", "Bedrock AgentCore Runtime", "BedrockAgentCoreApp entrypoint with invoke kinds sweep, answer, intake, status. Built and tested locally. Blocked by account quotas of 0."],
        ],
        "notes": "Seven more components: the household layer, the store, the notifier, the API, the dashboard, and the two deployments.",
    },
    {
        "id": "dataflow-1",
        "kind": "table",
        "bg": "paper",
        "eyebrow": "Data flow · 1 of 2",
        "h2": "One night, step by step: feeds to the verifier",
        "widths": [90, 1610],
        "header": ["Step", "Description"],
        "rows": [
            ["1", "The systemd timer posts /api/sweep at 06:00 UTC. The service checks the daily budget and starts the nightly-sweep graph with the window and the trigger."],
            ["2", "feeds_refresh pulls the new records from CPSC, NHTSA (one query for each vehicle), and openFDA. It normalizes them into RecallRecord rows. expiry_scan reads the warranty windows and the notification budget."],
            ["3", "candidate_gen compares every item with every recall in code: exact keys, lexical similarity with brand overlap, and the sold window. It emits certain matches and candidate pairs."],
            ["4", "matcher (agent, map) adjudicates each candidate pair with a MatchVerdict. warranty (agent, map) writes the check-in questions for the windows that end soon."],
            ["5", "verdicts merges the certain matches, the verdicts, and the questions into one list."],
            ["6", "triage (agent) applies the severity rules and the budget. It returns a SurfacePlan: the channel, the severity, the decisions, and the SMS text."],
            ["7", "severity_check (verify) compares the plan with the deterministic severity pass. A rejection sends triage back one time with the reasons."],
        ],
        "notes": "Steps one to seven: from the timer to the verifier. Steps four, six, and seven are the only model calls.",
    },
    {
        "id": "dataflow-2",
        "kind": "table",
        "bg": "paper",
        "eyebrow": "Data flow · 2 of 2",
        "h2": "One night, step by step: the gate to the follow-up",
        "widths": [90, 1610],
        "header": ["Step", "Description"],
        "rows": [
            ["8", "The plan routes to household_decision when the channel is sms_now. Otherwise digest records the standard hazards for the weekly digest and the run completes."],
            ["9", "The gate raises a Strands interrupt. The run pauses on disk. The service writes one Decision row for each item, sends the SMS, and marks the match as surfaced."],
            ["10", "The household answers by the SMS link, the dashboard, or the CLI. The service records the answer. On the first approval, it writes the gate approval with all answers as JSON and resumes the run."],
            ["11", "answers turns the approval into the list of approved decisions. remedy (agent, map) writes an ActionReport for each one."],
            ["12", "followup sends each request one time (SES or outbox), records the action, closes the match, and schedules the follow-up after 10 business days."],
            ["13", "Every event goes to events.jsonl and to /api/events. The dashboard updates over SSE. The store mirrors to S3 after each change."],
        ],
        "notes": "Steps eight to thirteen: the gate, the answer, the remedy, and the follow-up. Step eleven is the last model call.",
    },
    {
        "id": "datamodel",
        "kind": "columns",
        "bg": "paper",
        "eyebrow": "Data and state",
        "h2": "Three stores, one bucket",
        "columns": [
            ("Household store", [
                "items: brand, model, UPC, purchase date, retailer, price, warranty term, VIN.",
                "recalls: normalized records from the three feeds, with the severity pass.",
                "matches: item, recall, stage, score, verdict, and the state: candidate, confirmed, surfaced, closed.",
                "decisions: headline, facts, options, state, answer, outcome, run id.",
                "activity, sweeps, outbox, prefs, household.",
            ]),
            ("Run store (gren)", [
                "state.json: the run, its input, the status of each node, totals, approvals.",
                "events.jsonl: the trace. The dashboard streams it.",
                "artifacts/: the prompt, the schema, the raw output, usage, and cost of every model call.",
                "tasks/ and approvals/: the gate records that resume a paused run.",
            ]),
            ("Sync and config", [
                "GUARDIAN_STATE_SYNC=1 mirrors both stores to the S3 state bucket after each change. A new instance pulls them at start.",
                "config/env in the bucket holds the runtime environment of the server.",
                "The JSON store follows the single-table DynamoDB design of the plan. A move to DynamoDB is a driver change.",
            ]),
        ],
        "notes": "The household store is the product state. The run store is the audit trail. S3 keeps both across instance replacements.",
    },
    {
        "id": "gate",
        "kind": "gate",
        "bg": "ink",
        "eyebrow": "The human gate",
        "h2": "One interrupt, durable on disk",
        "steps": [
            ("gate.waiting", "The graph raises a Strands interrupt at household_decision. The run status is paused."),
            ("Decision rows", "The service writes one Decision for each surfaced item and sends the SMS. The dashboard shows the same cards."),
            ("The answer", "SMS link, dashboard, or CLI. Snooze, decline, or approve. A decline applies at once."),
            ("Approval", "The first approval writes the gate approval with every answer as JSON and resumes the run."),
            ("Resume", "Completed nodes replay from the checkpoint. remedy and followup run for the approved items only."),
        ],
        "rules": [
            ("Batched answers", "The approval comment carries the answer for each decision. The answers reducer maps them to remedy."),
            ("Late answers fork", "An approval after the run resumed forks the run from the gate with a -late suffix. Nothing blocks."),
            ("72 hours", "A decision expires after 72 hours. A snooze returns at 08:00 the next day."),
            ("Once, never twice", "followup declares side_effect and requires_gate. The frozen constraints make it unreachable without an approval and run it one time."),
        ],
        "notes": "The gate is the product. It must survive a process exit, a late answer, and a second click. The engine enforces all three.",
    },
    {
        "id": "cost",
        "kind": "table",
        "bg": "paper",
        "eyebrow": "Cost and controls",
        "h2": "Cents per night, capped three times",
        "widths": [420, 380, 900],
        "header": ["Control", "Scope", "Value and effect"],
        "rows": [
            ["Quiet night", "the graph", "Zero model calls. The when conditions skip matcher, triage, and every node after them."],
            ["Model per node", "the spec", "Haiku 4.5 for extraction and verification. Opus 5 for the matcher and triage. Sonnet 5 for the remedy. A typical night with one ambiguous pair makes 4 to 6 calls."],
            ["gren budget.max_cost_usd", "one run", "$3.00. The engine fails the run when its own recorded spend exceeds the cap."],
            ["GUARDIAN_DAILY_BUDGET_USD", "the household", "$10 by default. The service refuses to start a sweep or an intake once the recorded spend of the day reaches it."],
            ["AWS Budgets", "the account", "A $50 monthly alert. AWS Budgets alert; they do not cap. A budget action can restrict an IAM user, never the root user."],
            ["First live sweep", "measured", "594 CPSC recalls, 3 NHTSA campaigns, 1,200 openFDA reports. 7,143 pairs in code. 3 pairs to the model. 235 s. $0.41."],
            ["Live instance", "EC2 t3.small", "About $0.60 a day. deploy_ec2.py down removes everything but the bucket."],
            ["Token gate", "the public dashboard", "GUARDIAN_API_TOKEN gates every POST, PUT, and DELETE. Reads stay open. Rotate the token with one update."],
        ],
        "notes": "Three caps stack: the run, the day, and the account alert. The largest saving is the quiet night with zero calls.",
    },
    {
        "id": "risks",
        "kind": "table",
        "bg": "paper",
        "eyebrow": "Risk assessment",
        "h2": "What can go wrong, and what catches it",
        "widths": [480, 150, 150, 920],
        "header": ["Risk", "Prob.", "Impact", "Mitigation"],
        "rows": [
            ["Bedrock stays unauthorized for the account", "medium", "high", "AWS Support case 178934068800881 is open. The graphs run unchanged on the Anthropic API with ANTHROPIC_API_KEY and GREN_BRIDGE=anthropic."],
            ["A feed changes its format or goes down", "medium", "medium", "Each feed fails alone. The others continue. Recorded fixtures cover the tests. The first sweep uses a 400-day window."],
            ["A false negative in matching", "low", "high", "Exact keys first, lexical with brand overlap second, then the model on the ambiguous pairs. The verifier sees the confirmed matches."],
            ["A false positive interrupts the household", "medium", "medium", "The verifier can reject the plan. The budget limits interrupts. Snooze and decline are one tap."],
            ["A remedy sent twice", "low", "high", "The side-effect node runs one time behind the gate. The frozen constraints forbid a retry without idempotency."],
            ["The household never answers", "high", "low", "A decision expires after 72 hours. Nothing is sent without an approval. The digest keeps the record."],
            ["The demo token leaks", "low", "low", "The token gates writes only. The daily cap bounds spend. A new token deploys in one update."],
        ],
        "notes": "The two risks that matter are Bedrock authorization and a double send. One has a fallback. The other is impossible by construction.",
    },
    {
        "id": "decisions",
        "kind": "table",
        "bg": "paper",
        "eyebrow": "Architecture decisions",
        "h2": "Why it is built this way",
        "widths": [560, 1140],
        "header": ["Decision", "Rationale"],
        "rows": [
            ["gren on Strands, not a bare agent loop", "A YAML graph is inspectable, testable on a mock provider, and bounded. The engine, not the model, owns retries, budgets, and gates."],
            ["Code first, model second", "Feed pagination, VIN decoding, UPC equality, and the sold window are code. Only the ambiguous pairs cost tokens. A quiet night is free."],
            ["An adversarial verifier with kill authority", "A second prompt agrees too often. A verifier that can reject and repair the plan catches the plan that interrupts for nothing."],
            ["Gates as Strands interrupts with a checkpoint on disk", "A household answers hours later. The process must be free to exit. Resume replays completed nodes with no new model calls."],
            ["A JSON store shaped like the DynamoDB design", "One file per entity keeps the beta simple. The shape matches the plan, so the move to DynamoDB is a driver change."],
            ["EC2 and Caddy today, AgentCore next", "The account quotas for AgentCore are 0 and only AWS Support can raise them. One instance gives a public HTTPS URL now. The AgentCore entrypoint is built."],
            ["Token gate and daily cap on the public demo", "Reads are open for judges. Writes need the token. The cap protects the account whatever happens."],
            ["The Agent flow tab as a full trace workbench", "An agent that acts at night must show its work in the morning. The workbench follows the execution UI of Kestra: overview, timeline, logs, replay."],
        ],
        "notes": "Eight decisions. Each one trades a little generality for a bound the household can trust.",
    },
    {
        "id": "environment",
        "kind": "columns",
        "bg": "paper",
        "eyebrow": "Environment setup and prerequisites",
        "h2": "What a new machine needs",
        "columns": [
            ("Account and access", [
                "An AWS account with a payment method. Region us-east-1.",
                "aws login --profile guardian (browser credentials, 12 h, renewable 90 days). No access keys in the repo.",
                "Bedrock authorization for the account. A new account answers Operation not allowed until AWS Support grants it.",
                "AgentCore quotas above 0 for the AgentCore path (agents, endpoints, versions). Support case only.",
            ]),
            ("Model access", [
                "Haiku 4.5: global.anthropic.claude-haiku-4-5-20251001-v1:0",
                "Sonnet 5: global.anthropic.claude-sonnet-5",
                "Opus 5: global.anthropic.claude-opus-5",
                "GREN_BRIDGE selects the provider: bedrock, anthropic, claude-code, or mock. ANTHROPIC_API_KEY is the fallback.",
            ]),
            ("Local tooling and environment", [
                "Python 3.11 or later, Node 22, Chrome for the screenshots.",
                "pip install -e ./gren[dev] -e .[dev], then cd web && npm ci.",
                "The .env file: GUARDIAN_DAILY_BUDGET_USD, GUARDIAN_S3_BUCKET, GUARDIAN_API_TOKEN, GUARDIAN_SES_FROM, GUARDIAN_FEEDS. See .env.example.",
                "Tests: GREN_ALLOW_MOCK=1 python -m pytest -q (48 tests, about 30 s).",
            ]),
        ],
        "notes": "Three groups: the account, the models, and the machine. The only blocker outside our control is the Bedrock authorization.",
    },
    {
        "id": "deployment",
        "kind": "deployment",
        "bg": "ink",
        "eyebrow": "Deployment",
        "h2": "One instance today, AgentCore next",
        "notes": "deploy_ec2.py uploads a release and the runtime environment to the state bucket. The instance installs itself from them. Caddy terminates TLS. A timer runs the sweep. The store mirrors back to the bucket.",
    },
    {
        "id": "checklist",
        "kind": "columns",
        "bg": "paper",
        "eyebrow": "Deployment checklist",
        "h2": "From a clean account to a live URL",
        "columns": [
            ("Prerequisites", [
                "1. Run aws login --profile guardian.",
                "2. Create the private state bucket: aws s3 mb s3://guardian-<account>-state.",
                "3. Fill .env: AWS_PROFILE, AWS_REGION, GUARDIAN_S3_BUCKET, GUARDIAN_DAILY_BUDGET_USD.",
                "4. Run python scripts/aws_check.py. It makes one tiny Bedrock call.",
            ]),
            ("Deploy", [
                "5. Run python scripts/deploy_ec2.py up. It builds the dashboard, uploads the release, and creates the role, the security group, the elastic IP, and the instance.",
                "6. Wait for the health check. The first boot takes about 90 seconds.",
                "7. Open the URL once with ?token=<GUARDIAN_API_TOKEN>.",
                "8. Push new code with python scripts/deploy_ec2.py update.",
            ]),
            ("Verify and operate", [
                "9. python scripts/deploy_ec2.py status: the instance, the URL, and the provider.",
                "10. python scripts/deploy_ec2.py logs: the boot log and the service journal over SSM.",
                "11. Start a sweep from the dashboard. Watch it on the Agent flow tab.",
                "12. python scripts/deploy_ec2.py down --yes removes everything but the bucket.",
            ]),
        ],
        "notes": "Twelve steps. No SSH key exists anywhere. Logs and commands go through SSM.",
    },
    {
        "id": "status",
        "kind": "columns",
        "bg": "paper",
        "eyebrow": "Status and roadmap",
        "h2": "Done, blocked, next",
        "columns": [
            ("Done", [
                "The nightly sweep and the intake graph run end to end on live feeds.",
                "The dashboard with the six pages and the trace workbench.",
                "The live deployment on EC2 with automatic HTTPS, S3 state sync, and the nightly timer.",
                "48 tests on the mock provider, including the gate, snoozes, late approvals, and a verifier repair.",
            ]),
            ("Blocked on AWS", [
                "Bedrock authorization for the account. Every model call answers Operation not allowed until AWS Support grants it.",
                "AgentCore Runtime. The account quotas are 0. The entrypoint is built and tested locally.",
                "SES delivery to a real sender. The sandbox needs a verified identity.",
            ]),
            ("Next", [
                "AgentCore Runtime, Memory, and Gateway.",
                "SMS by SNS with an origination number.",
                "Photo intake of receipts (the mailroom), grocery advisories, and class-action settlements: the Expanded tier of the plan.",
                "Cognito sign-in for more than one household.",
            ]),
        ],
        "notes": "The product works. Two AWS gates stand between the live server and a full run on Bedrock.",
    },
    {
        "id": "closing",
        "kind": "closing",
        "quote": "The best output of the agent is silence. The primary metric of the product is how rarely it must speak to you.",
        "mono": REPO,
        "mono2": f"live: {LIVE}",
        "eyebrow": "Apache-2.0 · Strands Agents SDK · Everyday Agents track",
        "notes": "Thank you.",
    },
]
